
from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class RuleSpec:
    id: str
    category: str
    tactic: str
    event_types: tuple[str, ...]
    severity: str
    risk: int
    terms: tuple[str, ...]
    mitre: str | None
    description: str
    recommendation: str

RULES = [
    RuleSpec("BRUTE_FORCE_LOGIN","Identity","Credential Access",("failed_login","auth_failure"),"medium",55,(),"T1110","Repeated authentication failure indicator; correlate by source, user and time window.","Review source IP, targeted accounts and failed-attempt volume."),
    RuleSpec("PASSWORD_SPRAY","Identity","Credential Access",("auth_failure","failed_login"),"high",78,("multiple accounts","password spray","spray"),"T1110.003","Password-spraying indicator across multiple accounts.","Correlate users and source addresses; enforce MFA and lockout policy."),
    RuleSpec("SUSPICIOUS_POWERSHELL","Execution","Command and Scripting Interpreter",("powershell_execution","process_creation"),"high",78,("powershell",),"T1059.001","PowerShell execution with suspicious context.","Review script content, parent process and network destinations."),
    RuleSpec("ENCODED_POWERSHELL","Execution","Command and Scripting Interpreter",("powershell_execution",),"critical",92,("encodedcommand","-enc","frombase64string","encoded powershell"),"T1059.001","Encoded or obfuscated PowerShell execution indicator.","Capture command line and script block telemetry; isolate only with corroboration."),
    RuleSpec("POWERSHELL_DOWNLOAD_CRADLE","Execution","Command and Scripting Interpreter",("powershell_execution",),"critical",94,("invoke-webrequest","iwr ","webclient","downloadstring","downloadfile"),"T1059.001","PowerShell download/execute pattern.","Inspect URL, parent process and child process behavior."),
    RuleSpec("LOLBIN_CERTUTIL","Execution","Ingress Tool Transfer",("process_creation","command_execution"),"high",82,("certutil -urlcache","certutil.exe -urlcache"),"T1105","Certutil used as a transfer utility.","Review destination, file hash and parent process."),
    RuleSpec("LOLBIN_MSHTA","Execution","Signed Binary Proxy Execution",("process_creation","command_execution"),"high",84,("mshta ","mshta.exe"),"T1218.005","MSHTA execution indicator.","Inspect script source and parent process."),
    RuleSpec("LOLBIN_RUNDLL32","Execution","Signed Binary Proxy Execution",("process_creation","command_execution"),"high",82,("rundll32 ","rundll32.exe"),"T1218.011","Rundll32 proxy execution indicator.","Validate DLL path, signer and command line."),
    RuleSpec("LOLBIN_REGSVR32","Execution","Signed Binary Proxy Execution",("process_creation","command_execution"),"high",82,("regsvr32 ","regsvr32.exe"),"T1218.010","Regsvr32 proxy execution indicator.","Review DLL/SCriptlet origin and process tree."),
    RuleSpec("LOLBIN_WSCRIPT","Execution","Command and Scripting Interpreter",("process_creation","command_execution"),"high",80,("wscript.exe","cscript.exe"),"T1059.005","Windows script host execution indicator.","Inspect script source and launch chain."),
    RuleSpec("WMI_EXECUTION","Execution","Windows Management Instrumentation",("process_creation","wmi_event","command_execution"),"high",82,("wmic ","wmic.exe","invoke-wmimethod","wmiprvse.exe"),"T1047","WMI execution indicator.","Investigate remote host, caller and spawned process."),
    RuleSpec("SUSPICIOUS_PROCESS","Execution","Command and Scripting Interpreter",("suspicious_process","process_creation"),"high",74,("cmd.exe /c","powershell","rundll32","regsvr32","mshta","wscript","cscript"),"T1059","Suspicious command interpreter or proxy-execution process chain.","Inspect parent/child process lineage and command line."),
    RuleSpec("CREDENTIAL_ACCESS","Credential Theft","OS Credential Dumping",("credential_access","process_creation","file_access"),"critical",98,("lsass","credential dump","sekurlsa","mimikatz","sam database","security hive","ntds.dit"),"T1003","Credential-access or credential-dumping indicator.","Validate privileged context and protect credential stores."),
    RuleSpec("LSASS_ACCESS","Credential Theft","OS Credential Dumping",("process_access","credential_access"),"critical",99,("lsass access","openprocess lsass","mini dump lsass","procdump lsass"),"T1003.001","Direct LSASS access or dump indicator.","Treat as high priority and preserve volatile evidence."),
    RuleSpec("KERBEROASTING","Credential Theft","Steal or Forge Authentication Certificates",("auth_activity","kerberos"),"high",86,("kerberoast","service ticket","rc4 ticket"),"T1558.003","Kerberoasting-like authentication activity.","Review SPNs, service accounts and source identity."),
    RuleSpec("DCSYNC","Credential Theft","OS Credential Dumping",("directory_replication","dcsync"),"critical",100,("dcsync","replicating directory changes","drsuapi"),"T1003.006","Directory replication abuse indicator.","Validate initiating principal and domain-controller activity."),
    RuleSpec("NEW_ADMIN_ACCOUNT","Persistence","Create Account",("new_admin_account","account_created","user_created"),"high",82,("admin","administrator","privileged account"),"T1136.002","New privileged account indicator.","Confirm change ticket and owner; disable unauthorized account."),
    RuleSpec("SCHEDULED_TASK_PERSISTENCE","Persistence","Scheduled Task/Job",("scheduled_task","task_created","persistence"),"high",80,("schtasks","scheduled task created","task scheduler","new scheduled task"),"T1053.005","Scheduled task persistence indicator.","Review task command, author and execution history."),
    RuleSpec("RUN_KEY_PERSISTENCE","Persistence","Boot or Logon Autostart Execution",("registry_change","persistence"),"high",78,("\\run","runonce","currentversion\\run"),"T1547.001","Windows Run/RunOnce persistence indicator.","Review registry value, signer and user context."),
    RuleSpec("SERVICE_PERSISTENCE","Persistence","Create or Modify System Process",("service_install","service_created","persistence"),"high",84,("service created","new service","sc.exe create","create service"),"T1543.003","Service-based persistence indicator.","Validate binary path, signer and initiating user."),
    RuleSpec("STARTUP_FOLDER_PERSISTENCE","Persistence","Boot or Logon Autostart Execution",("file_create","persistence"),"medium",68,("startup folder","\\startup\\"),"T1060","Startup-folder persistence indicator.","Review new files and initiating process."),
    RuleSpec("DEFENDER_TAMPERING","Defense Evasion","Impair Defenses",("security_tamper","configuration_change","process_creation"),"critical",96,("defender disabled","disable realtime","tamper protection disabled","set-mppreference -disablerealtimemonitoring","disable antivirus"),"T1562.001","Endpoint protection tampering indicator.","Verify administrator intent and restore protection."),
    RuleSpec("FIREWALL_DISABLED","Defense Evasion","Impair Defenses",("configuration_change","firewall_change"),"critical",92,("firewall off","firewall disabled","netsh advfirewall set allprofiles state off","ufw disable"),"T1562.004","Firewall disablement indicator.","Validate change and restore policy if unauthorized."),
    RuleSpec("AUDIT_LOG_CLEARED","Defense Evasion","Indicator Removal",("audit_log_cleared","event_log_cleared"),"critical",96,("security log cleared","wevtutil cl security","clear event log","audit log cleared"),"T1070.001","Security event-log clearing indicator.","Preserve remaining evidence and investigate preceding activity."),
    RuleSpec("SHADOW_COPY_DELETE","Impact","Inhibit System Recovery",("shadow_copy_delete","command_execution"),"critical",100,("vssadmin delete shadows","shadow copies deleted","wmic shadowcopy delete","delete shadow copies"),"T1490","Shadow-copy deletion indicator.","Escalate and preserve evidence; review ransomware signals."),
    RuleSpec("RANSOMWARE_BEHAVIOR","Impact","Data Encrypted for Impact",("ransomware_behavior","file_activity"),"critical",100,("mass file rename","encrypted files","ransom note","ransomware","file encryption burst"),"T1486","Ransomware-like file activity indicator.","Consider host isolation under approved incident playbook."),
    RuleSpec("PSEXEC_LATERAL","Lateral Movement","Remote Services",("process_creation","remote_service"),"high",88,("psexec","psexesvc"),"T1569.002","PsExec lateral movement indicator.","Identify source/destination and privileged account."),
    RuleSpec("WINRM_LATERAL","Lateral Movement","Windows Remote Management",("remote_service","process_creation"),"high",82,("winrm","winrs","wsman"),"T1021.006","Windows Remote Management activity indicator.","Review source, target and command activity."),
    RuleSpec("SMB_ADMIN_SHARE","Lateral Movement","SMB/Windows Admin Shares",("network_connection","file_access"),"high",78,("\\\\admin$","\\\\c$","smb admin share","admin share"),"T1021.002","Administrative SMB share activity indicator.","Correlate source host with interactive login and process activity."),
    RuleSpec("RDP_ACTIVITY","Lateral Movement","Remote Services",("rdp_login","remote_login"),"medium",55,("rdp login","remote desktop","terminal services"),"T1021.001","Remote Desktop activity requiring contextual review.","Confirm expected administrator or support activity."),
    RuleSpec("RDP_BRUTE_FORCE","Credential Access","Remote Services",("failed_login","rdp_login"),"high",84,("rdp","terminal services","3389"),"T1110","RDP authentication attack indicator.","Review failed attempts by source and user."),
    RuleSpec("NETWORK_SCANNING","Discovery","Network Service Scanning",("network_scan","network_connection"),"high",76,("port scan","network scan","service enumeration","masscan","nmap","syn scan"),"T1046","Network scanning or service enumeration indicator.","Identify scanner asset and scope of targets."),
    RuleSpec("DNS_TUNNELING","Command and Control","Application Layer Protocol",("dns_query","network_connection"),"high",84,("dns tunnel","long dns","high entropy dns","dns exfiltration"),"T1071.004","Potential DNS tunneling/exfiltration indicator.","Review query volume, entropy and destination domain."),
    RuleSpec("C2_BEACON","Command and Control","Application Layer Protocol",("network_connection","network_beacon"),"high",86,("periodic outbound","beacon","command and control","c2"),"T1071","Potential periodic C2 communication indicator.","Review interval, destination, process owner and reputation."),
    RuleSpec("SUSPICIOUS_EXTERNAL_CONNECTION","Command and Control","Application Layer Protocol",("network_connection","network_beacon"),"medium",62,("unknown external","suspicious outbound","tor","c2","command and control"),"T1071","Potentially suspicious outbound communication.","Review destination and initiating process."),
    RuleSpec("MACOS_LAUNCHAGENT","Persistence","Launch Agent",("macos_persistence","launchagent"),"high",78,("launchagent","launch agent","~/library/launchagents"),"T1543.001","macOS LaunchAgent persistence indicator.","Review plist content and signing context."),
    RuleSpec("MACOS_LAUNCHDAEMON","Persistence","Launch Daemon",("macos_persistence","launchdaemon"),"high",82,("launchdaemon","launch daemon"),"T1543.001","macOS LaunchDaemon persistence indicator.","Review service binary and launch context."),
    RuleSpec("MACOS_OSASCRIPT","Execution","Command and Scripting Interpreter",("process_creation","macos_execution"),"high",74,("osascript","applescript"),"T1059.002","AppleScript/osascript execution indicator.","Review script origin and parent process."),
    RuleSpec("MACOS_CURL_PIPE_SHELL","Execution","Command and Scripting Interpreter",("process_creation","command_execution"),"critical",90,("curl | bash","curl | sh","wget -o- | sh","curl http"),"T1059","macOS shell download-and-execute pattern.","Inspect remote content and originating process."),
    RuleSpec("MACOS_KEYCHAIN_DUMP","Credential Theft","Credentials from Password Stores",("credential_access","process_creation"),"critical",96,("security find-generic-password","keychain dump","dump keychain"),"T1555.001","macOS Keychain access indicator.","Validate initiating binary and user context."),
    RuleSpec("LINUX_CRON_PERSISTENCE","Persistence","Cron",("linux_persistence","cron_change"),"high",78,("crontab","cron job","/etc/cron"),"T1053.003","Linux cron persistence indicator.","Review cron entry and owner."),
    RuleSpec("LINUX_SYSTEMD_PERSISTENCE","Persistence","System Services",("linux_persistence","service_created"),"high",80,("systemctl enable","systemd service","/etc/systemd/system"),"T1543.002","Linux systemd persistence indicator.","Inspect unit file and executable."),
    RuleSpec("LINUX_AUTHORIZED_KEYS","Persistence","SSH Authorized Keys",("linux_persistence","file_create"),"high",80,("authorized_keys","ssh key added","id_rsa"),"T1098.004","SSH authorized-key persistence indicator.","Verify key owner and source."),
    RuleSpec("LINUX_SUDOERS_CHANGE","Privilege Escalation","Sudoers",("linux_privilege","file_modify"),"critical",93,("sudoers modified","/etc/sudoers","visudo"),"T1548.003","Sudoers privilege-modification indicator.","Confirm change and review granted commands."),
    RuleSpec("LINUX_SUID_CHANGE","Privilege Escalation","Setuid and Setgid",("linux_privilege","file_change"),"high",86,("chmod +s","setuid","suid binary"),"T1548.001","SUID/SGID privilege escalation indicator.","Review changed binary and file owner."),
    RuleSpec("LINUX_CURL_PIPE_BASH","Execution","Command and Scripting Interpreter",("command_execution","linux_execution"),"critical",92,("curl | bash","wget | bash","curl -s http"),"T1059.004","Linux download-and-execute shell pattern.","Inspect remote content before containment."),
    RuleSpec("ANDROID_ACCESSIBILITY_ABUSE","Defense Evasion","Abuse Elevation Control Mechanism",("android_abuse","mobile_event"),"high",82,("accessibility service abuse","accessibility service enabled"),"T1548","Android accessibility abuse indicator.","Validate installed package and accessibility owner."),
    RuleSpec("ANDROID_DEVICE_ADMIN","Persistence","Account Manipulation",("android_abuse","mobile_event"),"high",78,("device admin abuse","device administrator enabled"),"T1098","Unexpected Android device-administrator state.","Review application identity and management policy."),
    RuleSpec("ANDROID_UNKNOWN_SOURCES","Defense Evasion","Impair Defenses",("android_abuse","mobile_event"),"medium",62,("unknown sources enabled","sideloading enabled"),"T1562","Android sideloading-control change.","Verify enterprise policy and application source."),
    RuleSpec("ANDROID_OVERLAY","Credential Access","Input Capture",("android_abuse","mobile_event"),"high",80,("overlay attack","draw over other apps"),"T1056","Android overlay/input-capture indicator.","Review package and requested privileges."),
    RuleSpec("IOS_PROFILE_CHANGE","Persistence","Additional Cloud Roles",("ios_profile_change","mobile_event"),"high",74,("configuration profile","mdm profile changed","mobileconfig"),"T1098","Unexpected Apple device-management profile change.","Validate MDM provenance and profile signer."),
    RuleSpec("IOS_JAILBREAK_INDICATOR","Defense Evasion","Rootkit",("ios_integrity","mobile_event"),"critical",90,("jailbreak","cydia","rootless jailbreak"),"T1611","iOS integrity/jailbreak indicator.","Validate device compliance and management state."),
    RuleSpec("NETWORK_CONFIG_CHANGE","Defense Evasion","Impair Defenses",("network_config_change","configuration_change"),"high",82,("firewall rule changed","router config changed","switch config changed","acl modified","security policy changed"),"T1562.004","Network security configuration change indicator.","Validate change window and operator identity."),
    RuleSpec("NETWORK_ADMIN_LOGIN","Initial Access","Valid Accounts",("network_login","admin_login"),"medium",55,("admin login","network administrator login","privileged login"),"T1078","Privileged network-device login indicator.","Correlate with source address and change events."),
    RuleSpec("SNMP_CONFIG_CHANGE","Defense Evasion","Network Device Configuration",("network_config_change",),"high",80,("snmp community changed","snmp configuration changed"),"T1601","SNMP configuration change indicator.","Verify management-plane change and credentials."),
    RuleSpec("CLOUD_IAM_POLICY_CHANGE","Persistence","Account Manipulation",("cloud_iam_change","iam_policy_change"),"high",86,("iam policy changed","role policy attached","privilege policy attached"),"T1098","Cloud IAM privilege/policy modification indicator.","Review actor, target identity and change ticket."),
    RuleSpec("CLOUD_ACCESS_KEY_CREATED","Persistence","Create Account",("cloud_iam_change","access_key_created"),"high",82,("access key created","api key created","service account key"),"T1136","New cloud credential indicator.","Confirm owner and expected automation."),
    RuleSpec("CLOUD_PUBLIC_STORAGE","Exfiltration","Cloud Storage Object",("cloud_config_change","storage_change"),"high",84,("bucket public","public storage","anonymous read","allusers"),"T1530","Public cloud-storage exposure indicator.","Review exposure and restore least privilege."),
    RuleSpec("CLOUD_AUDIT_DISABLED","Defense Evasion","Impair Defenses",("cloud_config_change","audit_change"),"critical",94,("cloudtrail disabled","audit logging disabled","logging sink disabled"),"T1562.008","Cloud audit logging disablement indicator.","Restore logging and investigate initiating identity."),
    RuleSpec("CLOUD_ROOT_LOGIN","Credential Access","Valid Accounts",("cloud_login","root_login"),"critical",92,("root login","root account login","privileged root session"),"T1078","High-risk cloud privileged-login indicator.","Validate MFA, source and approved break-glass procedure."),
    RuleSpec("OAUTH_CONSENT_GRANT","Persistence","Additional Cloud Roles",("cloud_iam_change","oauth_consent"),"high",84,("oauth consent","application consent","delegated permission granted"),"T1098","Cloud OAuth consent/permission grant indicator.","Review application, scopes and administrator approval."),
    RuleSpec("UNUSUAL_LISTENER","Command and Control","Proxy",("network_listener","process_creation"),"high",76,("new listening port","unexpected listener","bind shell","reverse shell"),"T1090","Unexpected network listener indicator.","Review process owning the socket and exposure scope."),
    RuleSpec("REVERSE_SHELL","Command and Control","Non-Application Layer Protocol",("network_connection","process_creation"),"critical",99,("reverse shell","bind shell","/dev/tcp/","powershell -nop -w hidden"),"T1059","Potential reverse-shell behavior.","Preserve process tree and network context."),
    RuleSpec("DEFENSE_EVASION_HISTORY_CLEAR","Defense Evasion","Indicator Removal",("command_execution","linux_execution"),"high",82,("history -c","clear history","remove-item (get-psreadlineoption).historysavepath"),"T1070.003","Command-history clearing indicator.","Correlate with surrounding commands and sessions."),
    RuleSpec("DISK_WIPE_ACTIVITY","Impact","Data Destruction",("file_activity","command_execution"),"critical",96,("cipher /w","secure delete","diskpart clean","sdelete"),"T1485","Potential data-destruction indicator.","Escalate immediately and preserve forensic evidence."),
    RuleSpec("MFA_FATIGUE_BURST","Identity","Credential Access",("mfa_denial","authentication","mfa_event"),"high",86,("mfa fatigue","repeated push","push denial","number matching denied"),"T1621","Repeated MFA prompts or denials may indicate MFA fatigue abuse.","Correlate prompt count, source, user and device context; verify with the user."),
    RuleSpec("MFA_DISABLED","Identity","Impair Defenses",("mfa_change","iam_change","security_setting_change"),"critical",92,("mfa disabled","multifactor disabled","two factor disabled"),"T1556","MFA protection was disabled for an identity.","Validate change approval and restore MFA immediately when unauthorized."),
    RuleSpec("SESSION_TOKEN_REUSE","Credential Theft","Web Session Cookie",("session_anomaly","auth_activity"),"critical",94,("token reused","session token reused","replayed token","session replay"),"T1539","Possible session-token reuse across contexts.","Compare source, device and timing; revoke suspicious sessions."),
    RuleSpec("IMPOSSIBLE_TRAVEL","Identity","Valid Accounts",("login_success","auth_activity","cloud_login"),"high",82,("impossible travel","geovelocity anomaly","impossible location"),"T1078","Authentication activity indicates implausible geographic movement.","Validate device continuity, source IP and MFA evidence."),
    RuleSpec("NEW_DEVICE_LOGIN","Identity","Valid Accounts",("login_success","auth_activity"),"medium",58,("new device login","unrecognized device","new endpoint sign-in"),"T1078","Login from a previously unseen device context.","Review device posture, registration status and user confirmation."),
    RuleSpec("PRIVILEGED_ROLE_ASSIGNMENT","Privilege Escalation","Account Manipulation",("iam_change","role_change","privilege_change"),"high",84,("admin role assigned","global administrator","privileged role assigned","owner role"),"T1098","Privileged role assignment indicator.","Validate change ticket, actor and separation-of-duties controls."),
    RuleSpec("SERVICE_PRINCIPAL_CREATED","Persistence","Account Manipulation",("cloud_iam_change","service_principal_created"),"high",82,("service principal created","application identity created","service account created"),"T1136","New workload identity created in cloud IAM.","Verify owner, permissions and intended automation."),
    RuleSpec("WILDCARD_CLOUD_PERMISSION","Privilege Escalation","Account Manipulation",("cloud_iam_change","iam_policy_change"),"critical",96,("action *","resource *","administratoraccess","owneraccess","fullaccess"),"T1098","Overly broad cloud privilege grant indicator.","Replace wildcard permissions with least-privilege statements."),
    RuleSpec("CLOUD_MFA_BYPASS","Credential Access","Valid Accounts",("cloud_login","iam_change"),"critical",93,("login without mfa","mfa bypass","authentication context bypass"),"T1556","Cloud authentication path may have bypassed MFA requirements.","Verify conditional access and authentication-strength policy."),
    RuleSpec("CLOUD_SECURITY_GROUP_EXPOSURE","Initial Access","Valid Accounts",("cloud_config_change","network_config_change"),"high",88,("0.0.0.0/0","::/0","security group open to world","public inbound"),"T1190","Cloud security-group exposure to the public internet.","Restrict ingress to approved addresses and ports."),
    RuleSpec("CLOUD_SECRET_BULK_READ","Credential Access","Unsecured Credentials",("cloud_data_access","secret_access"),"critical",94,("list secrets","get secret","bulk secret access","secrets manager"),"T1552","Potential bulk secret-store access.","Confirm workload identity and scope; rotate exposed credentials if necessary."),
    RuleSpec("CLOUD_UNUSUAL_REGION","Discovery","Cloud Service Dashboard",("cloud_login","cloud_activity"),"medium",64,("unusual region","new region","region anomaly"),"T1526","Cloud activity originating from an unusual region.","Correlate with deployment inventory and expected travel/automation."),
    RuleSpec("AWS_TRAIL_TAMPER","Defense Evasion","Impair Defenses",("cloud_config_change","audit_change"),"critical",97,("cloudtrail stop","trail deleted","trail stopped","logging disabled"),"T1562.008","AWS-style audit trail tampering indicator.","Restore audit logging and investigate the initiating principal."),
    RuleSpec("AZURE_AUDIT_TAMPER","Defense Evasion","Impair Defenses",("cloud_config_change","audit_change"),"critical",97,("diagnostic setting deleted","activity log disabled","audit settings disabled"),"T1562.008","Cloud audit configuration tampering indicator.","Restore logging and validate privileged identity activity."),
    RuleSpec("OAUTH_HIGH_RISK_SCOPE","Persistence","Account Manipulation",("oauth_consent","cloud_iam_change"),"high",88,("mail.readwrite","files.readwrite","offline_access","directory.readwrite"),"T1098","High-impact OAuth permission grant indicator.","Review application publisher, consent actor and granted scopes."),
    RuleSpec("WINDOWS_AMSI_BYPASS","Defense Evasion","Impair Defenses",("powershell_execution","process_creation","security_tamper"),"critical",98,("amsiutils","amsiinitfailed","amsi bypass","amsi context"),"T1562.001","Potential AMSI bypass indicator.","Preserve command-line and script telemetry; validate process lineage."),
    RuleSpec("WINDOWS_BITSADMIN_TRANSFER","Execution","Ingress Tool Transfer",("process_creation","command_execution"),"high",81,("bitsadmin /transfer","bitsadmin.exe","bitsadmin /create"),"T1105","BITSAdmin transfer utility usage.","Review transfer source, destination and initiating process."),
    RuleSpec("WINDOWS_REGSVCS_REGASM","Execution","Signed Binary Proxy Execution",("process_creation","command_execution"),"high",82,("regsvcs.exe","regasm.exe"),"T1218",".NET registration utility execution indicator.","Inspect assembly path, signer and parent process."),
    RuleSpec("WINDOWS_FODHELPER_UAC","Privilege Escalation","Bypass User Account Control",("process_creation","registry_change"),"critical",93,("fodhelper.exe","ms-settings\\shell\\open\\command"),"T1548.002","Potential UAC bypass via fodhelper registry hijack.","Review registry modifications and child process execution."),
    RuleSpec("WINDOWS_EVENTLOG_STOP","Defense Evasion","Impair Defenses",("service_change","configuration_change"),"critical",90,("eventlog service stopped","wevtapi","windows event log stopped"),"T1562.002","Windows event logging service disruption indicator.","Validate administrative intent and preserve adjacent evidence."),
    RuleSpec("WINDOWS_WMI_PERSISTENCE","Persistence","Windows Management Instrumentation",("wmi_persistence","wmi_event"),"critical",91,("wmi event subscription","__eventfilter","commandlineeventconsumer","activescripteventconsumer"),"T1546.003","WMI event subscription persistence indicator.","Enumerate WMI subscriptions and identify the registering principal."),
    RuleSpec("WINDOWS_DLL_SEARCH_ORDER","Privilege Escalation","Hijack Execution Flow",("process_creation","dll_load"),"high",84,("dll search order","side-load","dll sideload","unsigned dll"),"T1574.001","Potential DLL search-order or side-loading activity.","Validate DLL path, signer and expected application dependencies."),
    RuleSpec("WINDOWS_BROWSER_CREDENTIAL_ACCESS","Credential Theft","Credentials from Web Browsers",("browser_credential_access","file_access"),"high",86,("login data","cookies sqlite","chrome login data","edge login data","browser credentials"),"T1555.003","Browser credential-store access indicator.","Identify process, user and protected browser profile."),
    RuleSpec("WINDOWS_NTDS_ACCESS","Credential Theft","OS Credential Dumping",("file_access","credential_access"),"critical",98,("ntds.dit","sam database copy","system hive","security hive"),"T1003.003","Active Directory credential database access indicator.","Preserve evidence and investigate privileged access path."),
    RuleSpec("WINDOWS_PRINTSPOOLER_ABUSE","Privilege Escalation","Exploitation for Privilege Escalation",("service_change","process_creation"),"high",85,("spoolsv","print spooler exploit","printnightmare"),"T1068","Print Spooler abuse indicator.","Validate patch level and process lineage."),
    RuleSpec("WINDOWS_RDP_SHADOWING","Lateral Movement","Remote Services",("rdp_session","remote_service"),"high",78,("remote assistance","shadow session","rdp shadow"),"T1021.001","Remote desktop shadowing or assistance indicator.","Confirm support activity and operator authorization."),
    RuleSpec("WINDOWS_NET_USER_ADMIN","Persistence","Account Manipulation",("command_execution","account_change"),"high",83,("net user /add","net localgroup administrators","localgroup administrators"),"T1098","Command-line account or local administrator modification indicator.","Validate actor, command line and change ticket."),
    RuleSpec("LINUX_SSH_BRUTE_FORCE","Credential Access","Brute Force",("failed_login","ssh_auth"),"high",82,("sshd","ssh failed","authentication failure","invalid user"),"T1110","Repeated Linux SSH authentication failure indicator.","Correlate source address and targeted account."),
    RuleSpec("LINUX_KERNEL_MODULE_LOAD","Privilege Escalation","Rootkit",("kernel_module","process_creation"),"critical",92,("insmod","modprobe","kernel module loaded","rootkit"),"T1547","Kernel module loading may indicate persistence or rootkit behavior.","Validate module signer, source and load context."),
    RuleSpec("LINUX_LD_PRELOAD","Persistence","Hijack Execution Flow",("environment_change","process_creation","file_modify"),"critical",90,("ld_preload","/etc/ld.so.preload"),"T1574.006","LD_PRELOAD hijacking indicator.","Inspect preload entries and affected processes."),
    RuleSpec("LINUX_ETC_HOSTS_CHANGE","Defense Evasion","Impair Defenses",("file_modify","dns_change"),"medium",61,("/etc/hosts","hosts file modified"),"T1565","Local name-resolution manipulation indicator.","Review modified entries and initiating process."),
    RuleSpec("LINUX_SSH_CONFIG_TAMPER","Persistence","SSH Authorized Keys",("file_modify","ssh_config_change"),"high",80,("sshd_config","permitrootlogin","authorizedkeyscommand"),"T1098.004","SSH configuration persistence or access-policy change indicator.","Validate configuration and source of change."),
    RuleSpec("LINUX_DOCKER_SOCKET_ACCESS","Privilege Escalation","Container Administration Command",("file_access","process_creation"),"high",83,("docker.sock","/var/run/docker.sock"),"T1611","Docker socket access can provide host-level privilege.","Identify container or process accessing the socket and its trust boundary."),
    RuleSpec("MACOS_TCC_DATABASE_ACCESS","Credential Access","Credentials from Password Stores",("macos_privacy","file_access"),"critical",91,("tcc.db","tccutil","privacy database"),"T1555","macOS privacy-control database access indicator.","Review process signer, user context and affected permissions."),
    RuleSpec("MACOS_GATEKEEPER_DISABLED","Defense Evasion","Impair Defenses",("security_tamper","configuration_change"),"high",84,("gatekeeper disabled","spctl --master-disable","assessments disabled"),"T1562.001","macOS Gatekeeper security control change.","Validate administrative intent and restore policy when unauthorized."),
    RuleSpec("MACOS_KEXT_LOAD","Persistence","Kernel Modules and Extensions",("kernel_extension","process_creation"),"critical",90,("kextload","kernel extension loaded","system extension"),"T1547","macOS kernel/system-extension load indicator.","Validate signer and approved management policy."),
    RuleSpec("MACOS_SCREEN_CAPTURE_PERMISSION","Credential Access","Input Capture",("macos_privacy","permission_change"),"high",79,("screen recording permission","screen capture permission","tcc screen capture"),"T1113","Unexpected screen-capture permission activity.","Review requesting application and management approval."),
    RuleSpec("ARP_SPOOFING","Discovery","Network Service Scanning",("arp_anomaly","network_anomaly"),"critical",95,("arp spoof","duplicate mac","gratuitous arp anomaly","arp conflict"),"T1557.002","Potential ARP spoofing or local man-in-the-middle indicator.","Validate switch CAM/ARP state and isolate only under approved response."),
    RuleSpec("ROGUE_DHCP","Initial Access","Network Service Scanning",("dhcp_anomaly","network_anomaly"),"high",84,("rogue dhcp","multiple dhcp servers","unexpected dhcp offer"),"T1557","Potential rogue DHCP service detected.","Identify offering MAC/IP and verify against authorized infrastructure."),
    RuleSpec("ROGUE_DNS","Command and Control","Application Layer Protocol",("dns_anomaly","network_anomaly"),"high",81,("rogue dns","unexpected dns server","dns hijack"),"T1071.004","Potential DNS infrastructure manipulation.","Verify resolver configuration and upstream path."),
    RuleSpec("WEAK_PROTOCOL_TELNET","Credential Access","Network Service Scanning",("network_service","network_connection"),"medium",58,("telnet","port 23","cleartext management"),"T1040","Cleartext network management protocol observed.","Replace Telnet with encrypted management protocols."),
    RuleSpec("UNEXPECTED_EXTERNAL_ADMIN","Lateral Movement","Remote Services",("network_connection","admin_login"),"high",81,("external admin","remote admin internet","ssh from internet","rdp from internet"),"T1021","Administrative remote service reachable from an external source.","Restrict exposure and verify source identity."),
    RuleSpec("FIRMWARE_CHANGE","Defense Evasion","System Firmware",("firmware_change","configuration_change"),"critical",90,("firmware update","firmware changed","boot firmware changed"),"T1542.001","Unexpected device firmware modification indicator.","Validate vendor update, signer and maintenance window."),
    RuleSpec("NETWORK_CONFIG_BACKUP_EXPORT","Collection","Automated Collection",("network_config_export","configuration_export"),"medium",65,("config export","running config export","backup configuration"),"T1005","Network configuration export activity.","Verify destination security and operator authorization."),
    RuleSpec("WAF_SQL_INJECTION","Initial Access","Exploit Public-Facing Application",("http_request","waf_event"),"high",87,("union select","or 1=1","sqlmap","select from","sleep("),"T1190","Potential SQL injection pattern in web traffic.","Validate WAF action, request source and target endpoint."),
    RuleSpec("WAF_XSS","Initial Access","Exploit Public-Facing Application",("http_request","waf_event"),"high",80,("<script>","javascript:","onerror=","onload="),"T1190","Potential cross-site scripting payload observed.","Confirm WAF handling and inspect affected endpoint."),
    RuleSpec("WAF_SSRF","Initial Access","Server Side Request Forgery",("http_request","waf_event"),"critical",91,("169.254.169.254","metadata endpoint","gopher://","file://localhost","ssrf"),"T1190","Potential SSRF request targeting internal resources.","Inspect destination normalization and application response."),
    RuleSpec("WAF_PATH_TRAVERSAL","Initial Access","Exploitation for Client Execution",("http_request","waf_event"),"high",79,("../","..\\","%2e%2e","etc/passwd","windows/system32"),"T1190","Potential path traversal request.","Review request normalization and affected resource."),
    RuleSpec("WAF_COMMAND_INJECTION","Execution","Command and Scripting Interpreter",("http_request","waf_event"),"critical",94,(";whoami","| whoami","&& powershell",";id","|bash"),"T1059","Potential command injection payload in web traffic.","Preserve request context and review spawned process telemetry."),
    RuleSpec("BOT_CREDENTIAL_STUFFING","Credential Access","Brute Force",("http_request","auth_failure"),"high",83,("credential stuffing","automated login","bot login burst","password reuse"),"T1110.004","Credential-stuffing pattern against an authentication endpoint.","Correlate source reputation, user spread and challenge outcomes."),
    RuleSpec("RATE_LIMIT_BYPASS","Defense Evasion","Proxy",("waf_event","http_request"),"medium",64,("rate limit bypass","rotating ip","distributed requests"),"T1090","Potential rate-limit evasion pattern.","Review client identifiers, source distribution and WAF controls."),
    RuleSpec("ANDROID_SIDeload","Initial Access","User Execution",("android_app","mobile_event"),"high",79,("sideloaded app","unknown source app","apk install"),"T1204","Android application installation from an unapproved source.","Validate package signer and enterprise application policy."),
    RuleSpec("ANDROID_MDM_UNENROLL","Defense Evasion","Impair Defenses",("mdm_event","mobile_event"),"critical",93,("mdm unenrolled","management removed","device management disabled"),"T1562","Mobile management controls were removed.","Re-enroll device and investigate initiating identity."),
    RuleSpec("IOS_MDM_UNENROLL","Defense Evasion","Impair Defenses",("mdm_event","mobile_event"),"critical",93,("mdm unenrolled","management removed","device management disabled"),"T1562","Apple device-management controls were removed.","Re-enroll device and verify identity activity."),
    RuleSpec("IOT_DEFAULT_CREDENTIAL","Credential Access","Valid Accounts",("iot_event","authentication"),"high",77,("default password","admin/admin","root/admin","default credentials"),"T1078","IoT device using known default credentials.","Rotate credentials and disable unused management interfaces."),
    RuleSpec("IOT_OUTBOUND_ANOMALY","Command and Control","Application Layer Protocol",("iot_network_event","network_connection"),"high",78,("unexpected outbound","unknown destination","iot anomaly","rare destination"),"T1071","Unexpected IoT outbound communication.","Review destination, device firmware and expected vendor telemetry."),
    RuleSpec("UNEXPECTED_PRIVILEGED_SESSION","Privilege Escalation","Valid Accounts",("privileged_login","admin_login"),"high",80,("privileged session","break glass","emergency admin"),"T1078","Privileged session requires elevated contextual review.","Correlate MFA, source device and approved emergency procedure."),
    RuleSpec("MISSING_SECURITY_AGENT","Defense Evasion","Impair Defenses",("device_posture","agent_status"),"high",82,("agent missing","sensor offline","security agent stopped"),"T1562.001","Endpoint security sensor is missing or unavailable.","Validate sensor health and restore telemetry collection."),
    RuleSpec("EDR_TAMPER","Defense Evasion","Impair Defenses",("security_tamper","agent_status"),"critical",97,("edr stopped","sensor tampered","security service stopped","agent disabled"),"T1562.001","Endpoint detection and response control tampering indicator.","Treat as priority telemetry and validate authorized maintenance."),
    RuleSpec("BACKUP_DELETE","Impact","Inhibit System Recovery",("backup_change","file_activity","command_execution"),"critical",96,("backup deleted","remove backup","delete recovery points","backup retention changed"),"T1490","Backup or recovery-point deletion indicator.","Correlate with ransomware activity and preserve recovery options."),
    RuleSpec("DATA_STAGING_ARCHIVE","Collection","Archive Collected Data",("file_activity","data_access"),"high",83,("7z archive","rar archive","zip archive","tar archive","data staging"),"T1560","Potential data-staging/archive activity.","Inspect file source, destination, size and initiating identity."),
    RuleSpec("LARGE_OUTBOUND_TRANSFER","Exfiltration","Exfiltration Over Web Service",("network_connection","data_transfer"),"high",86,("large upload","large outbound transfer","exfiltration","bulk upload"),"T1567","Potential large outbound data transfer.","Correlate byte volume, destination reputation and data classification."),
    RuleSpec("SUSPICIOUS_CLOUD_STORAGE_DOWNLOAD","Collection","Archive Collected Data",("cloud_data_access","storage_download"),"high",80,("bulk object download","mass download","cloud storage export"),"T1530","Potential bulk cloud-storage download.","Validate user, application and data volume."),
    RuleSpec("SECRETS_ENUMERATION","Discovery","Cloud Service Dashboard",("cloud_iam_change","cloud_discovery"),"high",78,("list secrets","enumerate secrets","list credentials","list access keys"),"T1552","Secrets or credential-object enumeration indicator.","Review caller identity, scope and subsequent access."),
    RuleSpec("UNUSUAL_API_KEY_USE","Credential Access","Valid Accounts",("cloud_api","cloud_activity"),"high",85,("api key from new ip","api key from new device","unknown automation identity"),"T1078","Cloud API credential use from an unusual context.","Validate source, owner and workload identity."),
]

# v4.2.8 enterprise extension rules: network exposure, IDS/IPS, vulnerability and identity signals.
RULES.extend([
    RuleSpec("IDS_SURICATA_CRITICAL","Network Detection","Command and Control",("ids_alert","suricata_alert"),"critical",94,("suricata", "critical"),"T1040","Critical alert produced by a Suricata sensor.","Validate the signature, source/destination context and sensor confidence before containment."),
    RuleSpec("IDS_SNORT_HIGH","Network Detection","Network Service Scanning",("ids_alert","snort_alert"),"high",84,("snort", "high"),"T1046","High-confidence Snort alert observed.","Review the Snort rule, packet context and affected asset."),
    RuleSpec("IDS_RDP_EXPOSURE","Network Exposure","Remote Services",("network_service","ids_alert"),"high",70,("rdp","3389","remote desktop"),"T1021.001","RDP exposure or access activity detected.","Restrict RDP to authorized management networks and review authentication telemetry."),
    RuleSpec("IDS_SMB_EXPOSURE","Network Exposure","Remote Services",("network_service","ids_alert"),"high",72,("smb","445","admin share"),"T1021.002","SMB exposure or access activity detected.","Restrict SMB scope and review patch posture and authentication events."),
    RuleSpec("NETWORK_TELNET_EXPOSURE","Network Exposure","Remote Services",("network_service","vulnerability_found"),"high",78,("telnet","port 23"),"T1021","Unencrypted Telnet management exposure detected.","Disable Telnet and move management to encrypted protocols."),
    RuleSpec("NETWORK_FTP_EXPOSURE","Network Exposure","Remote Services",("network_service","vulnerability_found"),"medium",58,("ftp","port 21"),"T1021","FTP service exposure detected.","Prefer SFTP/FTPS and limit source networks."),
    RuleSpec("NETWORK_RDP_EXPOSURE","Network Exposure","Remote Services",("network_service","vulnerability_found"),"high",68,("rdp","port 3389"),"T1021.001","RDP service exposure detected.","Restrict RDP and require strong authentication."),
    RuleSpec("NETWORK_SMB_EXPOSURE","Network Exposure","Remote Services",("network_service","vulnerability_found"),"high",72,("smb","port 445"),"T1021.002","SMB service exposure detected.","Restrict SMB and confirm current patching."),
    RuleSpec("VULN_CRITICAL_FINDING","Vulnerability","Exploitation for Client Execution",("vulnerability_found","vulnerability_scan"),"critical",96,("critical","cve","vulnerable"),"T1203","Critical vulnerability finding reported by the assessment layer.","Confirm the finding, prioritize patching/mitigation and reassess the asset."),
    RuleSpec("VULN_HIGH_FINDING","Vulnerability","Exploitation for Client Execution",("vulnerability_found","vulnerability_scan"),"high",84,("high","cve","vulnerable"),"T1203","High-risk vulnerability finding reported by the assessment layer.","Validate evidence and remediate the affected service."),
    RuleSpec("VULN_LEGACY_SERVICE","Vulnerability","Exploitation for Client Execution",("vulnerability_found",),"medium",62,("legacy service","unsupported service","outdated"),"T1190","Legacy or unsupported service exposure detected.","Upgrade, disable or isolate the service according to the asset owner."),
    RuleSpec("WEB_ADMIN_PANEL_EXPOSURE","Network Exposure","Exploit Public-Facing Application",("http_request","network_service","vulnerability_found"),"high",80,("admin panel","management console","8080","8443"),"T1190","Administrative web interface may be reachable from a broader network than intended.","Restrict source networks, require MFA and place the interface behind an access gateway."),
    RuleSpec("SNMP_WEAK_POSTURE","Network Exposure","Network Service Scanning",("network_service","vulnerability_found"),"medium",63,("snmp","community string","161"),"T1046","SNMP management exposure detected.","Use SNMPv3 and restrict management sources."),
    RuleSpec("WINRM_HTTP_EXPOSURE","Network Exposure","Remote Services",("network_service","vulnerability_found"),"medium",61,("winrm","5985"),"T1021.006","WinRM over HTTP exposure detected.","Prefer WinRM HTTPS and restrict administration sources."),
    RuleSpec("PRINTER_RAW_PORT","Network Exposure","Exfiltration Over Alternative Protocol",("network_service","vulnerability_found"),"low",42,("printer","9100","raw printing"),"T1048","Raw printer service is reachable.","Restrict printer management and raw print traffic to trusted infrastructure."),
    RuleSpec("IDS_DNS_ANOMALY","Network Detection","Application Layer Protocol",("ids_alert","dns_alert"),"high",82,("dns anomaly","dns tunnel","suspicious dns"),"T1071.004","DNS anomaly reported by the network sensor.","Inspect query volume, domain age/reputation and resolver path."),
    RuleSpec("IDS_HTTP_EXPLOIT","Network Detection","Exploit Public-Facing Application",("ids_alert","waf_event"),"high",88,("sql injection","path traversal","ssrf","command injection"),"T1190","Network sensor identified an application-layer exploit pattern.","Preserve request evidence and validate server-side telemetry."),
    RuleSpec("IDS_LATERAL_MOVEMENT","Network Detection","Lateral Movement",("ids_alert","network_anomaly"),"high",86,("lateral movement","east-west","pass-the-hash","remote admin burst"),"T1021","Network sensor reported potential lateral movement.","Correlate source asset, destination assets and identity telemetry."),
    RuleSpec("IDS_BEACONING","Network Detection","Command and Control",("ids_alert","network_connection"),"high",88,("beacon","periodic callback","c2"),"T1071","Periodic outbound network behavior may indicate command-and-control activity.","Review timing, destination reputation and endpoint process lineage."),
    RuleSpec("ASSET_POSTURE_CRITICAL","Posture","Impair Defenses",("device_posture","posture_change"),"critical",92,("critical posture","security agent disabled","encryption disabled"),"T1562","Critical endpoint posture degradation detected.","Restore security controls and review the initiating identity."),
    RuleSpec("ASSET_NEW_ADMIN","Identity","Account Manipulation",("admin_account","privileged_account"),"high",82,("new administrator","local admin","privileged account"),"T1098","New privileged account activity detected.","Validate change ticket, source identity and MFA state."),
    RuleSpec("AGENT_KEY_MISMATCH","Defense Evasion","Impair Defenses",("collector_auth_failure","agent_event"),"high",77,("agent key invalid","collector unauthorized"),"T1562.001","Telemetry collector authentication failure detected.","Verify the agent identity and rotate the collector credential if required."),
    RuleSpec("SURICATA_EVE_GAP","Defense Evasion","Impair Defenses",("sensor_health","ids_status"),"high",80,("eve log stale","suricata stale","sensor offline"),"T1562.001","Suricata telemetry has become stale or unavailable.","Restore sensor health and verify the capture interface."),
    RuleSpec("SNORT_SENSOR_GAP","Defense Evasion","Impair Defenses",("sensor_health","ids_status"),"high",80,("snort stale","snort offline","sensor offline"),"T1562.001","Snort telemetry has become stale or unavailable.","Restore sensor health and verify DAQ/interface configuration."),
])


MITRE_MAP = {r.id:r.mitre for r in RULES}


def ensure_rule_states(db):
    from app.models.rule_state import RuleState
    from datetime import datetime
    existing = {x.rule_id:x for x in db.query(RuleState).all()}
    changed=False
    for r in RULES:
        if r.id not in existing:
            db.add(RuleState(rule_id=r.id, enabled=True, updated_at=datetime.utcnow())); changed=True
    if changed: db.commit()


def detect_event(event_type: str, message: str | None = None, db=None):
    et=(event_type or '').lower().replace(' ','_')
    msg=(message or '').lower()
    corpus=f"{et} {msg}"
    states={}
    if db:
        from app.models.rule_state import RuleState
        states={x.rule_id:x.enabled for x in db.query(RuleState).all()}
    matches=[]
    for r in RULES:
        if states.get(r.id, True) is False: continue
        type_hit = (et in r.event_types) or any(alias in et for alias in r.event_types)
        term_hit = True if not r.terms else any(t.lower() in corpus for t in r.terms)
        if type_hit and term_hit:
            matches.append(r)
    if not matches and et=='failed_login':
        r=next(x for x in RULES if x.id=='BRUTE_FORCE_LOGIN')
        if states.get(r.id,True): matches=[r]
    if not matches:
        return {'detected':False,'rule':None,'severity':'low','risk_score':0,'description':'No detection rule matched.','mitre_technique':None,'recommendation':None,'matched_rules':[]}
    matches.sort(key=lambda x:x.risk, reverse=True)
    r=matches[0]
    return {'detected':True,'rule':r.id,'severity':r.severity,'risk_score':r.risk,'description':r.description,'mitre_technique':r.mitre,'recommendation':r.recommendation,'matched_rules':[x.id for x in matches[:8]]}
